name: Docker Image CI
# Define trigger conditions that result in CI pipeline workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Configure set of actions that will be performed once triggered
  build:

    runs-on: ubuntu-latest

    steps:
    # A github repository named 'checkout' ( ref - github.com/actions/checkout ) contains an action yaml file defining actions to be performed in order to checkout 
    - uses: actions/checkout@v3
    - name: creating env files
      run: |
        touch .appenv .mongoenv
        echo ${{ secrets.MONGO }} >> .appenv
        echo ${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> .mongoenv
        echo ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> .mongoenv
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Setup docker compose stack
      run: docker compose up -d
    - name: testing
      run: |
        bash e2e.sh
        docker compose down
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: stav352/portfolio:latest
