name: Docker Image CI
# Define trigger conditions that result in CI pipeline workflow
on:
  push:
    branches:
    - "main"
    - 'feature/**'
  pull_request:
    branches:
    - "main"
    - "feature/**"

jobs:
  # Configure set of actions that will be performed once triggered
  build:

    runs-on: ubuntu-latest

    steps:
    # A github repository named 'checkout' ( ref - github.com/actions/checkout ) contains an action yaml file defining actions to be performed in order to checkout 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        # Creates the environment variables required for the build in a secure manner
        echo "${{ secrets.MONGO }}" > .appenv
        echo "${{ secrets.MONGODB_CREDS }}" > .mongoenv
        docker compose up --build -d

    - name: E2E Testing
      run: |
        # Waits the required time in order for tests to run successfully.
        sleep 4
        bash ./e2e.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: stav352/portfolio:latest
